In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
c = np.array(np.arange(10))

In [6]:
c.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
d = c.reshape((2, 5))

In [8]:
e = d.ravel()

In [9]:
e[3] = 100

In [10]:
f = d.flatten()

In [11]:
f[4] = 200

In [12]:
a.dtype

dtype('int32')

In [13]:
a.astype(np.int8)

array([1, 2, 3], dtype=int8)

In [14]:
a.dtype

dtype('int32')

In [15]:
a = a.astype(np.int8)

In [16]:
a.dtype

dtype('int8')

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b[:, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b[:, 1]

array([2, 5])

In [20]:
b[:, [1]]

array([[2],
       [5]])

In [21]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

In [22]:
b[:, 1:]

array([[2, 3],
       [5, 6]])

In [23]:
b[1, :]

array([4, 5, 6])

In [24]:
b[1, 1]

5

In [25]:
b[1, 1:]

array([5, 6])

In [26]:
b[1, [0, 2]]

array([4, 6])

In [27]:
b[:, [1]]

array([[2],
       [5]])

In [28]:
b[:, [1]].flatten()

array([2, 5])

In [29]:
b[:, [1, 2]].flatten()

array([2, 3, 5, 6])

In [30]:
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b[:, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [36]:
np.random.random((3, 2))

array([[0.86966353, 0.56688763],
       [0.2630304 , 0.81740221],
       [0.6502679 , 0.80601893]])

In [37]:
np.random.seed(123)

In [38]:
np.random.random()

0.6964691855978616

In [39]:
np.random.seed(123)

In [40]:
np.random.random()

0.6964691855978616

In [41]:
np.random.seed(123)

In [42]:
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [43]:
np.random.seed(123)

In [44]:
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [45]:
np.random.seed(123)

In [46]:
np.random.rand(3, 2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [47]:
np.random.seed(123)

# NG
no arguments is not allowed.

In[]: np.random.randint()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)  
<ipython-input-175-68ea1e0699a6> in <module>  
      1 #  
----> 2 np.random.randint()  
  
mtrand.pyx in mtrand.RandomState.randint()  
  
TypeError: randint() takes at least 1 positional argument (0 given)  

In [48]:
np.random.random()

0.6964691855978616

In [49]:
np.random.rand()

0.28613933495037946

In [50]:
np.random.seed(123)

In [51]:
np.random.randint(100)

66

In [52]:
np.random.seed(123)

In [53]:
# 0 <= ret < 100
np.random.randint(low=100)

66

In [54]:
# 1 <= ret < 10
np.random.randint(1, 10)

3

In [55]:
# 1 <= ret < 10
np.random.randint(low=1, high=10)

7

In [56]:
np.random.randint(1, 10, (3, 4))

array([[2, 4, 7, 2],
       [1, 2, 1, 1],
       [4, 5, 1, 1]])

In [57]:
np.random.uniform(1, 10, (3, 4))

array([[7.64195865, 2.64242557, 2.57906581, 5.78396236],
       [5.78644828, 6.70960863, 8.64488615, 7.52009792],
       [6.4992116 , 7.50199044, 3.90663022, 4.2560979 ]])

In [58]:
np.random.uniform(1.0, 10.0, (3, 4))

array([[3.05436908, 3.64342642, 6.67878511, 1.82894446],
       [4.90331055, 4.87776487, 5.44316588, 4.83247261],
       [3.81035101, 4.83716176, 9.04050247, 9.49744016]])

In [59]:
# default : 0.0 <= ret < 1.0
np.random.uniform()

0.5018366758843366

In [60]:
# default : 0.0 <= ret < 1.0
np.random.uniform(size=(3, 4))

array([[0.62395295, 0.1156184 , 0.31728548, 0.41482621],
       [0.86630916, 0.25045537, 0.48303426, 0.98555979],
       [0.51948512, 0.61289453, 0.12062867, 0.8263408 ]])

In [61]:
np.random.randn(4, 2)

array([[ 0.97873601,  2.23814334],
       [-1.29408532, -1.03878821],
       [ 1.74371223, -0.79806274],
       [ 0.02968323,  1.06931597]])

In [62]:
np.random.randn(4, 2, 3)

array([[[ 0.89070639,  1.75488618,  1.49564414],
        [ 1.06939267, -0.77270871,  0.79486267]],

       [[ 0.31427199, -1.32626546,  1.41729905],
        [ 0.80723653,  0.04549008, -0.23309206]],

       [[-1.19830114,  0.19952407,  0.46843912],
        [-0.83115498,  1.16220405, -1.09720305]],

       [[-2.12310035,  1.03972709, -0.40336604],
        [-0.12602959, -0.83751672, -1.60596276]]])

In [63]:
np.random.normal()

1.2552373747242185

In [64]:
np.random.seed(123)

In [65]:
# default
# loc = average
# scale = dispersion
np.random.normal(loc=0.0, scale=1.0, size=None)

-1.0856306033005612

In [66]:
np.random.seed(123)

In [67]:
# same as default of 'normal'
np.random.randn()

-1.0856306033005612

In [68]:
np.random.seed(123)

In [69]:
np.random.normal(size=(4, 3, 2))

array([[[-1.0856306 ,  0.99734545],
        [ 0.2829785 , -1.50629471],
        [-0.57860025,  1.65143654]],

       [[-2.42667924, -0.42891263],
        [ 1.26593626, -0.8667404 ],
        [-0.67888615, -0.09470897]],

       [[ 1.49138963, -0.638902  ],
        [-0.44398196, -0.43435128],
        [ 2.20593008,  2.18678609]],

       [[ 1.0040539 ,  0.3861864 ],
        [ 0.73736858,  1.49073203],
        [-0.93583387,  1.17582904]]])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
np.ones(3)

array([1., 1., 1.])

In [76]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
np.ones((3, 2, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [80]:
np.eye(1)

array([[1.]])

In [82]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.full(3, np.pi)

array([3.14159265, 3.14159265, 3.14159265])

In [85]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [86]:
np.full((5, 3, 2), np.pi)

array([[[3.14159265, 3.14159265],
        [3.14159265, 3.14159265],
        [3.14159265, 3.14159265]],

       [[3.14159265, 3.14159265],
        [3.14159265, 3.14159265],
        [3.14159265, 3.14159265]],

       [[3.14159265, 3.14159265],
        [3.14159265, 3.14159265],
        [3.14159265, 3.14159265]],

       [[3.14159265, 3.14159265],
        [3.14159265, 3.14159265],
        [3.14159265, 3.14159265]],

       [[3.14159265, 3.14159265],
        [3.14159265, 3.14159265],
        [3.14159265, 3.14159265]]])

In [87]:
np.full((4, 3), np.random.rand())

array([[0.36178866, 0.36178866, 0.36178866],
       [0.36178866, 0.36178866, 0.36178866],
       [0.36178866, 0.36178866, 0.36178866],
       [0.36178866, 0.36178866, 0.36178866]])

In [88]:
np.full((4, 3), np.random.uniform(1, 100))

array([[23.59805986, 23.59805986, 23.59805986],
       [23.59805986, 23.59805986, 23.59805986],
       [23.59805986, 23.59805986, 23.59805986],
       [23.59805986, 23.59805986, 23.59805986]])

In [89]:
np.full((4, 3), np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [93]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [94]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [95]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [97]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [98]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [100]:
# Same as:
np.arange(0, 10.1, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [102]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])